name: ci

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - tests/**
      - docs/**

jobs: 
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install PowerShell dependencies
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module platyps, PSScriptAnalyzer -force

      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          Invoke-ScriptAnalyzer -Path .\ -Settings PSGallery -Recurse -ReportSummary -Severity Error

      - name: Run Tests
        shell: pwsh
        continue-on-error: true
        run: |
          Invoke-Pester -ci

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: Pester-Tests
          path: testResults.xml

      - name: Generate public help
        shell: pwsh
        run: |
          Remove-Module PSMDE -Force -ErrorAction SilentlyContinue
          Remove-item .\docs\ -Recurse -Force
          Remove-item .\en-us\ -Recurse -Force
          Import-Module .\src\PSMDE.psd1
          $parameters = @{
            Module = 'PSMDE'
            OutputFolder = 'docs'
            AlphabeticParamsOrder = $true
            WithModulePage = $true
            ExcludeDontShow = $true
            Encoding = [System.Text.Encoding]::UTF8
          }
          New-MarkdownHelp @parameters -Force
          New-ExternalHelp -Path '.\docs' -OutputPath '.\en-us'

      - name: Upload public help
        uses: LanceMcCarthy/Action-AzureBlobUpload@v2
        with:
          connection_string: ${{ secrets.STORAGE_CONNECTION_STRING }}
          container_name: help
          source_folder: en-us
          delete_if_exists: true

      - name: Bump version and tag
        uses: mathieudutour/github-tag-action@v6.0
        id: tag_version
        with:
          github_token: ${{ secrets.PSMDE_REPO }}
          release_branches: main

      - name: Update manifest and help version
        if: ${{ steps.tag_version.outputs.new_tag }}
        shell: pwsh
        env:
          TAG_NAME: ${{ steps.tag_version.outputs.new_tag }}
        run: |
          $release = $env:TAG_NAME.replace('v', '')
          $help = Get-Content ./docs/PSMDE.md
          $help = $help | foreach-object { $_ -replace '(?<prefix>^.?Help Version: )(.+)(?<suffix>)$', "`${prefix}$release`${suffix}" }
          $help | Out-File ./docs/PSMDE.md -Force -Encoding ascii
          $manifest = Get-Content ./src/PSMDE.psd1
          $manifest = $manifest | foreach-object { $_ -replace "(?<prefix>^\s+ModuleVersion     = ')(.+)(?<suffix>')$", "`${prefix}$release`${suffix}" } 
          $manifest | Out-File ./src/PSMDE.psd1 -Force -Encoding ascii

      - name: Commit updated markdown help and version files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs(external-help): :memo: Updated external help"
          commit_user_email: jdamaschke@visorian.com
          branch: main
