name: test

on:
  pull_request:
    branches:    
      - main

jobs: 
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install PowerShell dependencies
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module platyps, PSScriptAnalyzer -force

      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          Invoke-ScriptAnalyzer -Path .\ -Settings PSGallery -Recurse -ReportSummary -Severity Error

      - name: Run Tests
        shell: pwsh
        continue-on-error: true
        run: |
          $config = New-PesterConfiguration -Hashtable @{TestResult = @{Enabled = $true }; Run = @{Exit = $true }; CodeCoverage = @{Enabled = $true } }
          Invoke-Pester -Configuration $config

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: Pester-Tests
          path: testResults.xml

      - name: Upload code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: Pester-Tests
          path: coverage.xml